[pytest]
addopts = -ra
testpaths =
    services/engine/tests
    services/worker/tests
    services/api/tests
    database/tests
    tests
pythonpath =
    services/engine/src
    services/worker/src
    services/api/src
    database/src
